### ISSUE TITLE
TK#19 Desarrollo aplicacion de chat.

### ISSUE THREAD

**Issue by cesarweb** [FullStackCatamarca/proyecto_g3-proyecto_g3#11]

**Comment by JonathanCastillo-dv** [comment]
![image](https://user-images.githubusercontent.com/63659773/107855454-2a61b080-6e01-11eb-8d63-7fd6df3d14cb.png)
![image](https://user-images.githubusercontent.com/63659773/107855469-3d748080-6e01-11eb-96ef-197911446ac3.png)
![image](https://user-images.githubusercontent.com/63659773/107855491-4f562380-6e01-11eb-9a64-3178ee98b605.png)
![Sin título](https://user-images.githubusercontent.com/63659773/107855552-cb506b80-6e01-11eb-8007-af73a62be4a7.png)
![Sin título2](https://user-images.githubusercontent.com/63659773/107855553-cbe90200-6e01-11eb-9898-d308ece11136.png)

**El chatBot Fue agregado en el archivo _Layout.cshtml, al final del </head> (es un Script)
Este Chatbot nos permite generar unas plantillas de conversación para poder resolver diferentes consultas del usuario.**
