### ISSUE TITLE
TK#22 Instalacion de C# Clonar Repositorios Hacer Holamundo Jhony.

### ISSUE THREAD

**Issue by cesarweb** [FullStackCatamarca/proyecto_g3-proyecto_g3#9]

**Comment by JonathanCastillo-dv** [comment]
**Mi Primer Hola mundo en C# 😄** 
![image](https://user-images.githubusercontent.com/63659773/106833915-2f8d6580-6673-11eb-837c-c04fbae272bb.png)
![image](https://user-images.githubusercontent.com/63659773/106833939-37e5a080-6673-11eb-880e-8cbbc2b8c103.png)
